// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/consensus.proto

package backend // import "github.com/hyperledger/fabric/orderer/consensus/sbft/backend"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import simplebft "github.com/hyperledger/fabric/orderer/consensus/sbft/simplebft"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Handshake struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_f2db4dd0e8c462b7, []int{0}
}
func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (dst *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(dst, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Handshake)(nil), "backend.handshake")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsensusClient is the client API for Consensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsensusClient interface {
	Consensus(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (Consensus_ConsensusClient, error)
}

type consensusClient struct {
	cc *grpc.ClientConn
}

func NewConsensusClient(cc *grpc.ClientConn) ConsensusClient {
	return &consensusClient{cc}
}

func (c *consensusClient) Consensus(ctx context.Context, in *Handshake, opts ...grpc.CallOption) (Consensus_ConsensusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Consensus_serviceDesc.Streams[0], "/backend.consensus/consensus", opts...)
	if err != nil {
		return nil, err
	}
	x := &consensusConsensusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Consensus_ConsensusClient interface {
	Recv() (*simplebft.MultiChainMsg, error)
	grpc.ClientStream
}

type consensusConsensusClient struct {
	grpc.ClientStream
}

func (x *consensusConsensusClient) Recv() (*simplebft.MultiChainMsg, error) {
	m := new(simplebft.MultiChainMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConsensusServer is the server API for Consensus service.
type ConsensusServer interface {
	Consensus(*Handshake, Consensus_ConsensusServer) error
}

func RegisterConsensusServer(s *grpc.Server, srv ConsensusServer) {
	s.RegisterService(&_Consensus_serviceDesc, srv)
}

func _Consensus_Consensus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Handshake)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsensusServer).Consensus(m, &consensusConsensusServer{stream})
}

type Consensus_ConsensusServer interface {
	Send(*simplebft.MultiChainMsg) error
	grpc.ServerStream
}

type consensusConsensusServer struct {
	grpc.ServerStream
}

func (x *consensusConsensusServer) Send(m *simplebft.MultiChainMsg) error {
	return x.ServerStream.SendMsg(m)
}

var _Consensus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.consensus",
	HandlerType: (*ConsensusServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "consensus",
			Handler:       _Consensus_Consensus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend/consensus.proto",
}

func init() { proto.RegisterFile("backend/consensus.proto", fileDescriptor_consensus_f2db4dd0e8c462b7) }

var fileDescriptor_consensus_f2db4dd0e8c462b7 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xbd, 0x0e, 0x82, 0x40,
	0x0c, 0x80, 0x75, 0xd1, 0x80, 0x1b, 0x8b, 0xca, 0xc8, 0x03, 0x5c, 0x8d, 0xae, 0xea, 0xa0, 0x9b,
	0x09, 0x2f, 0xe0, 0x76, 0x3f, 0x85, 0xbb, 0x00, 0x77, 0xa4, 0x3d, 0x06, 0xdf, 0xde, 0xa8, 0x04,
	0xdc, 0xda, 0xf4, 0xcb, 0xd7, 0x2f, 0xdd, 0x2a, 0xa9, 0x1b, 0xf4, 0x06, 0x74, 0xf0, 0x8c, 0x9e,
	0x07, 0x16, 0x3d, 0x85, 0x18, 0xb2, 0xf5, 0x78, 0xc8, 0xf7, 0xec, 0xba, 0xbe, 0x45, 0x55, 0x45,
	0x98, 0xa6, 0x1f, 0x53, 0x6c, 0xd2, 0xc4, 0x4a, 0x6f, 0xd8, 0xca, 0x06, 0x8f, 0x8f, 0x34, 0x99,
	0x1c, 0xd9, 0xe5, 0x7f, 0xc9, 0xc4, 0xe8, 0x12, 0x13, 0x9d, 0xef, 0xc4, 0x2c, 0x2b, 0x87, 0x36,
	0xba, 0xbb, 0x95, 0xce, 0x97, 0x5c, 0x17, 0x8b, 0xc3, 0xf2, 0x76, 0x7d, 0x9e, 0x6b, 0x17, 0xed,
	0xa0, 0x84, 0x0e, 0x1d, 0xd8, 0x57, 0x8f, 0xd4, 0xa2, 0xa9, 0x91, 0xa0, 0x92, 0x8a, 0x9c, 0x86,
	0x40, 0x06, 0x09, 0x69, 0xae, 0x06, 0xfe, 0x04, 0x8e, 0x7f, 0xd4, 0xea, 0xdb, 0x77, 0x7a, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xcb, 0x0b, 0x73, 0x26, 0xde, 0x00, 0x00, 0x00,
}
