// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderer/sbft/configuration.proto

package sbft // import "github.com/hyperledger/fabric/protos/orderer/sbft"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "etcdraft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_e7770eb43a098b4b, []int{0}
}
func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (dst *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(dst, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,3,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_e7770eb43a098b4b, []int{1}
}
func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (dst *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(dst, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Defines the SBFT parameters when 'sbft' is specified as the 'OrdererType'
type Options struct {
	N                    uint32   `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	F                    uint32   `protobuf:"varint,2,opt,name=f,proto3" json:"f,omitempty"`
	RequestTimeoutNsec   uint32   `protobuf:"varint,3,opt,name=request_timeout_nsec,json=requestTimeoutNsec,proto3" json:"request_timeout_nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_configuration_e7770eb43a098b4b, []int{2}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (dst *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(dst, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *Options) GetF() uint32 {
	if m != nil {
		return m.F
	}
	return 0
}

func (m *Options) GetRequestTimeoutNsec() uint32 {
	if m != nil {
		return m.RequestTimeoutNsec
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "sbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "sbft.Consenter")
	proto.RegisterType((*Options)(nil), "sbft.Options")
}

func init() {
	proto.RegisterFile("orderer/sbft/configuration.proto", fileDescriptor_configuration_e7770eb43a098b4b)
}

var fileDescriptor_configuration_e7770eb43a098b4b = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x59, 0x5b, 0x2c, 0xdd, 0x36, 0x16, 0x16, 0x0f, 0x39, 0x86, 0x1e, 0x34, 0x78, 0xc8,
	0x6a, 0xfd, 0x07, 0xf6, 0xac, 0xc2, 0x52, 0x10, 0xbc, 0x84, 0x64, 0x3b, 0x49, 0x23, 0xe9, 0x6e,
	0x9c, 0x9d, 0x08, 0x9e, 0xfd, 0xe3, 0x92, 0xdd, 0x54, 0x7b, 0x9b, 0x7d, 0xef, 0x9b, 0x79, 0xcb,
	0x0c, 0x4f, 0x2c, 0xee, 0x01, 0x01, 0xa5, 0x2b, 0x2b, 0x92, 0xda, 0x9a, 0xaa, 0xa9, 0x7b, 0x2c,
	0xa8, 0xb1, 0x26, 0xeb, 0xd0, 0x92, 0x15, 0xd3, 0xc1, 0x59, 0x7f, 0xf0, 0xab, 0xad, 0x37, 0x9f,
	0x81, 0x8a, 0x7d, 0x41, 0x85, 0x90, 0x9c, 0x6b, 0x6b, 0x1c, 0x18, 0x02, 0x74, 0x31, 0x4b, 0x26,
	0xe9, 0x62, 0xb3, 0xca, 0x06, 0x38, 0xdb, 0x9e, 0x74, 0x75, 0x86, 0x88, 0x5b, 0x3e, 0xb3, 0xdd,
	0x30, 0xd8, 0xc5, 0x17, 0x09, 0x4b, 0x17, 0x9b, 0x28, 0xd0, 0xaf, 0x41, 0x54, 0x27, 0x77, 0xfd,
	0xc3, 0xf8, 0xfc, 0x6f, 0x84, 0x10, 0x7c, 0x7a, 0xb0, 0x8e, 0x62, 0x96, 0xb0, 0x74, 0xae, 0x7c,
	0x3d, 0x68, 0x9d, 0x45, 0xf2, 0x73, 0x22, 0xe5, 0x6b, 0x71, 0xc3, 0x57, 0xba, 0x6d, 0xc0, 0x50,
	0x4e, 0xad, 0xcb, 0x35, 0x20, 0xc5, 0x93, 0x84, 0xa5, 0x4b, 0x15, 0x05, 0x79, 0xd7, 0xba, 0x2d,
	0x04, 0xce, 0x01, 0x7e, 0x01, 0xfe, 0x73, 0xd3, 0xc0, 0x05, 0x79, 0xe4, 0xd6, 0x6f, 0x7c, 0x36,
	0xfe, 0x4c, 0x2c, 0x39, 0x33, 0x3e, 0x3f, 0x52, 0xcc, 0x0c, 0xaf, 0x6a, 0x4c, 0x66, 0x95, 0xb8,
	0xe7, 0xd7, 0x08, 0x9f, 0x3d, 0x38, 0xca, 0xa9, 0x39, 0x82, 0xed, 0x29, 0x37, 0x0e, 0xb4, 0xcf,
	0x8e, 0x94, 0x18, 0xbd, 0x5d, 0xb0, 0x5e, 0x1c, 0xe8, 0xa7, 0x9c, 0xdf, 0x59, 0xac, 0xb3, 0xc3,
	0x77, 0x07, 0xd8, 0xc2, 0xbe, 0x06, 0xcc, 0xaa, 0xa2, 0xc4, 0x46, 0x87, 0x85, 0xbb, 0x6c, 0x3c,
	0x89, 0xdf, 0xce, 0xfb, 0x43, 0xdd, 0xd0, 0xa1, 0x2f, 0x33, 0x6d, 0x8f, 0xf2, 0xac, 0x45, 0x86,
	0x16, 0x19, 0x5a, 0xe4, 0xf9, 0x15, 0xcb, 0x4b, 0x2f, 0x3e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x16, 0x09, 0x1f, 0x12, 0xdc, 0x01, 0x00, 0x00,
}
